### ISSUE TITLE
Function to add feed

### ISSUE THREAD

**Issue by PubliAlex** [rezozero/mixedfeed#15]
Hello,

I'm trying to generate feed (thanks to your plugin) in a configurable way.

I would like to do something like that :

    <?php
        $mixedFeed = new MixedFeed;
        if(!empty($twitter_user_id)) {
            $mixedFeed->addFeed(new TwitterFeed(.....));
        }
        if(!empty($facebook_page_id)) {
            $mixedFeed->addFeed(new FacebookPageFeed(......));
        }
        //  etc....
        return $mixedFeed->getAsyncCanonicalItems(12);
    ?>

I looked at your MixedFeed.php file, but unfortunately, I didn't find any method that allow to add feed like that. Based on your code example, I wonder how can I add conditions to add only needed feeds based on external configuration.

Thank you for your module

Regards,

Alex

**Comment by ambroisemaupate** [comment]
Hi @AlexandreZeiller 

Does this way could suit you ?

```php
$feeds = [
    new InstagramFeed(
        'instagram_user_id',
        'instagram_access_token',
        null // you can add a doctrine cache provider
    )
];
if(!empty($twitter_user_id)) {
     $feeds[] = new TwitterFeed(.....);
}
if(!empty($facebook_page_id)) {
    $feeds[] = new FacebookPageFeed(......);
}

$mixedFeed = new MixedFeed(feeds);
return $mixedFeed->getAsyncCanonicalItems(12);
```

**Comment by PubliAlex** [comment]
Ah, yes, it perfectly does the job. Thank you for a sooo rapid answer !
