### ISSUE TITLE
Can't make MediumFeed to work

### ISSUE THREAD

**Issue by PubliAlex** [rezozero/mixedfeed#16]
Hello,

I'm trying to make MediumFeed to work, I would successfully user Facebook and Twitter until now.

Here is my code :

            $feeds[] = new MediumFeed(
                '@ElonMuu',
            );

the documentation say it only require a user name, so I try with Elon Musk one, but it return : 

>Error contacting medium feed provider: Client error: `GET > https://medium.com/@ElonMuu/latest?format=json&limit=6&source=latest` resulted in a `403 Forbidden` response

Did I miss something ?

Thanks

Alex

**Comment by ambroisemaupate** [comment]
I think you're hitting Cloudflare mitigating page. If you are retrying later it should be ok. 

Try to use Medium endpoint with user ID instead of username. It should be more stable.
