### ISSUE TITLE
Facebook API default version

### ISSUE THREAD

**Issue by glafarge** [rezozero/mixedfeed#18]
The library makes calls to Facebook's Graph API without specifying a version number.

https://github.com/rezozero/mixedfeed/blob/dac67636d99586431c351402d828c52f5dfa283a/src/FacebookPageFeed.php#L109-L112

I think the library should implement an option to set the version or configure the endpoint (base url).

What Facebook says about that :

> **What happens if I don't specify a version for an API?**
>
> We refer to this as an **unversioned** call. An unversioned call will default to the oldest available version of the API. Consider this hypothetical life cycle of API versions:
> 
> ![image](https://user-images.githubusercontent.com/670645/66491521-23ab8680-eab3-11e9-8ad9-3fc53ef11bac.png)
> 
> An unversioned call will always point to the oldest version still available at the top of the chart. This is currently v2.1, but after two years it'll be v2.2, then v2.3, etc.
> 
> Because of this, our recommendation is to always specify versions when making calls, where possible.
> 
> When using the JavaScript SDK for Facebook you can't make unversioned API calls.

https://developers.facebook.com/docs/apps/versions/?locale=en_US

**Comment by ambroisemaupate** [comment]
Hi @glafarge 

Thank you for your feedback!

Could you provide a PR for this change ?

**Comment by glafarge** [comment]
Done ;) Hope code is OK.

**Comment by ambroisemaupate** [comment]
BTW I’m just curious, did you pass Facebook validation to use your App with `Public Content View` permission ?

**Comment by glafarge** [comment]
To start : Facebook app review is a nightmare !

Since many weeks, a lot of app we created before are now in pending review. We don't use `Public Content View`: review team are more strict with it as it gives the access to all Facebook pages (not only yours or those you manage).

`Page Public Content Access` is only used to read and analyze from all other pages (the review team is very strict with this permission), whereas permissions such as `manage_page` are used for the use of the developer or the client logging into the developer's app. 
`Manage_pages` permission is also used to display the content from your own facebook page to your own website.

We have passed the validation for apps that uses `manage_pages` permission but it has required a screencast showing the sourcecode of the app (and the use of your lib), because a simple screencast that shows only the result (the feed on the website) is not enough for them.

**Comment by ambroisemaupate** [comment]
I’ve just read this article, https://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token

But your app admin must be your FB Page admin too, but it is way more easier and do not require App Review.

**Comment by glafarge** [comment]
Thank you for the link 😉 We already use a never expiring tokens (generated using our little php script), but Facebook asked us to complete the validation process the last month. Maybe we have not understanding correctly their message or the rules changed with API updates, but we've done it and this was not easy...
No problems on this topic on your end ?

**Comment by ambroisemaupate** [comment]
Facebook refused our App Reviews too when requesting access_page_content. So we need to ask review using manage_page permission and ask each of our client to become admin for their app. We'll see ...

**Comment by glafarge** [comment]
Facebook become a little bit complicated in my opinion...
I have opened ticket with Facebook staff during the validation process ; don't hesitate to do it : they can help to expedite the process with review team for you.

**Comment by ambroisemaupate** [comment]
Thanks for the tip!
