### ISSUE TITLE
FacebookPageFeed unsupported fields

### ISSUE THREAD

**Issue by robertromore** [rezozero/mixedfeed#21]
I'm trying to fetch some facebook page posts using this library. I'm using a recently created facebook app and I'm getting errors similar to the following: "link field is deprecated for versions v3.3 and higher". This is happening for the link, source, and type fields. Since my app is newer, the API call is automatically using the oldest supported API, which in my case I'm guessing is >=3.3. 

According to https://developers.facebook.com/docs/apps/versions/, certain apps that are old enough can continue using older versions of the API. 

The way the code is written at https://github.com/rezozero/mixedfeed/blob/master/src/FacebookPageFeed.php#L90, it doesn't look like I can remove fields, only add fields to the array initialized at line 78. Is there a way to adjust the final array of fields that will be used?

**Comment by ambroisemaupate** [comment]
Hello @robertromore 

Thanks for your feedback.    
Next release v3.1.1 will fix this.
