### ISSUE TITLE
Facebook and Instagram issues

### ISSUE THREAD

**Issue by cwahlfeldt** [rezozero/mixedfeed#22]
First off I just wanna say thanks for making an awesome package! This is definitely a time saver. However I would love to actually utilize the package with facebook and instagram but in my recent experience it seems extremely difficult to get access to those api's. Does anyone have any experience getting access to facebook and instagram? My team and I were recently denied access to the permissions we requested. It seems like there has to be an easier, more user friendly way to do this.

Thanks!
Chris

**Comment by maximseshuk** [comment]
t

**Comment by DenisNikonov** [comment]
asdf

**Comment by ambroisemaupate** [comment]
Hello,
We did not used Facebook API since their changes. 
Using Facebook *BasicInstagram* API you always can package your own instagram feed, but you'll need to renew your access-token every 3 months. We added a new FeedProvider GraphInstragram for that.
