### ISSUE TITLE
Cache interop

### ISSUE THREAD

**Issue by nlemoine** [rezozero/mixedfeed#23]
Hi!

Thanks for this library. 

Cache actually relies on doctrine/cache which is not up to date and more importantly is not suitable for providing another library.

Would you agree to switch a more standard cache? For instance PSR-6 interface?

**Comment by ambroisemaupate** [comment]
Hello @nlemoine 

Thanks for your suggestion. I think this is a great idea!
Do you have the time to submit a pull-request for this change ? Then we could release a new major version not to break projects that rely on Doctrine cache.

**Comment by ambroisemaupate** [comment]
https://github.com/rezozero/mixedfeed/pull/24 fixes this.
