### ISSUE TITLE
is this package compatible with laravel 5.3.X?

### ISSUE THREAD

**Issue by KhushbuThakkar** [rezozero/mixedfeed#6]
hi, i wanted to try this package for 5.3.x.

Can you tell me it has required changes made for 5.3.X ?

**Comment by ambroisemaupate** [comment]
Hi 

We didn't test mixedfeed on Laravel yet. We are using Roadiz and Symfony. 

Feel free to test it and tell us if it's OK. We accept PR for improving documentation on other frameworks.
