### ISSUE TITLE
Feed from ecommerce platforms

### ISSUE THREAD

**Issue by ronlinet** [rezozero/mixedfeed#9]
Do you plan to also aggregate feeds from ecommerce platforms such as amazon, ebay, smashwords? 
I am asking because I am planing to build such an aggregator and I am hesitating between forking  this project or simply include my work here.

**Comment by ambroisemaupate** [comment]
Hi @ronlinet 

We do not plan to add other non-social-network platforms. Feel free to fork and pull request once you’ve added your custom `Providers`.
